name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

jobs:
  publish:
    name: publish crate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: cargo publish (dry-run)
        if: github.event_name == 'pull_request'
        run: cargo publish --dry-run

      - name: cargo publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
